workflow:
  rules:
    - if: $CI_COMMIT_BRANCH !="main" && $CI_PIPELINE_SOURCE !="merge_request_event"
      when: never
    - when: always


variables:
  GIT_SSL_NO_VERIFY: 'true'

stages:
  - build
  - deploy

build_image:
  stage: build
  cache:
    key: '$CI_COMMIT_REF_NAME'
    paths:
      - ./node_modules  
  tags: 
    - debtor_monit_front_shell  
  script:
    - echo $CI_PROJECT_DIR
    - npm config set legacy-peer-deps true
    - npm i
    - npm run build
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker-compose -f docker-compose.yml build
    #- docker build -t registry.flexit.uz/flexit/veolia_customer:latest .

push_image:
  stage: build
  needs:
    - build_image
  tags:
    - debtor_monit_front_shell
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push registry.flexit.uz/flexit/lendo/client/debtor-monit-front:latest

deploy_to_dev:
  stage: deploy
  tags:
    - debtor_monit_front_dev
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull registry.flexit.uz/flexit/lendo/client/debtor-monit-front:latest
    - docker-compose up -d


