workflow:
  rules:
    - if: $CI_COMMIT_BRANCH !="main" && $CI_PIPELINE_SOURCE !="merge_request_event"
      when: never
    - when: always


variables:
  GIT_SSL_NO_VERIFY: 'true'

stages:
  - build_app
  - build_image
  - deploy

build_app:
  stage: build_app
  image: node:16.18.1
  tags: 
    - debtor_monit_front_docker
  cache:
    key: '$CI_COMMIT_REF_NAME'
    paths:
      - ./node_modules  
  script:
    - pwd
    - npm config set legacy-peer-deps true
    - npm i
    - npm run build
    - rm -rf /builds/flexit/lendo/client/debtor-monit-front/node_modules
    - pwd
    - ls -la
  artifacts:
      when: always
      name: "Docker executor artifact"
      paths: 
        - /builds/flexit/lendo/client/debtor-monit-front
        
build_image:
  stage: build_image
  image: docker
  services:
    - docker:dind
  tags:
    - debtor_monit_front_docker
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose  
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker-compose -f docker-compose.yml build
    #- docker build -t registry.flexit.uz/flexit/veolia_customer:latest .

push_image:
  stage: build_image
  needs:
    - build_image
  image: docker
  services:
    - docker:dind  
  tags:
    - debtor_monit_front_docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push registry.flexit.uz/flexit/lendo/client/debtor-monit-front:latest

deploy_to_dev:
  stage: deploy
  tags:
    - debtor_monit_front_dev
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull registry.flexit.uz/flexit/lendo/client/debtor-monit-front:latest
    - docker-compose up -d


