version: "3.8"

services:
  debtor-monit-front:
    restart: always
    container_name: debtor-monit-front
    image: registry.flexit.uz/flexit/lendo/client/debtor-monit-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DBURL=https://cc.lendo.uz/api
      - DBURL2=https://cc.lendo.uz/api2
      - AUTHURL=https://auth.flexit.uz/auth
      - WSURL=wss://cc.lendo.uz
      - FILEURL=http://dev.lendo.uz/files
    ports:
      - "1223:1222"
